CREATE TABLE accounts (
    id INT PRIMARY KEY,
    balance INT
);

INSERT INTO accounts VALUES (1, 500);

SELECT @@transaction_isolation; -- Query current isolation level

-- ISSUE 1: DIRTY READ
SESSION 1:
SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
START TRANSACTION;
SELECT * FROM accounts WHERE id = 1;

SESSION 2:
SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
START TRANSACTION;
SELECT * FROM accounts WHERE id = 1;

-- ISSUE 2: LOST UPDATE
-- -- SESSION 1:
SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
START TRANSACTION;
SELECT balance FROM accounts WHERE id = 1;
UPDATE accounts SET balance = 600 WHERE id = 1;
-- do NOT COMMIT yet

-- -- SESSION 2:
SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
START TRANSACTION;
SELECT balance FROM accounts WHERE id = 1;
UPDATE accounts SET balance = 450 WHERE id = 1;
COMMIT;

-- SESSION 1:
COMMIT;

SELECT * FROM accounts WHERE id = 1;

-- ISSUE 3: Non-Repeatable Read
-- -- SESSION 1:
SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
START TRANSACTION;
SELECT balance FROM accounts WHERE id = 1;

-- -- SESSION 2:
START TRANSACTION;
UPDATE accounts SET balance = 700 WHERE id = 1;
COMMIT;

-- -- SESSION 1:
SELECT balance FROM accounts WHERE id = 1;
COMMIT;

-- -- ISSUE 4: Phantom Read
-- -- SESSION 1:
SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
START TRANSACTION;
SELECT * FROM accounts WHERE balance >= 500; -- 1 row

-- -- SESSION 2:
SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
START TRANSACTION;
INSERT INTO accounts VALUES (2, 1000);
COMMIT;

-- -- SESSION 1:
SELECT * FROM accounts WHERE balance >= 500; -- 1 row
COMMIT;


-- ISOLATION LEVELS
-- REPEATABLE READS
INSERT INTO accounts values (2, 1000);

-- Scenario 1: When the table has been read by session 1 
--             before id = 2 was deleted
-- SESSION 1:
SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
START TRANSACTION;
SELECT * FROM accounts;

-- SESSION 2:
SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
START TRANSACTION;
DELETE FROM accounts WHERE id = 2;
COMMIT;

-- Scenario 2: When the before id = 2 was deleted before session 1 reads the table
-- SESSION 2: 
START TRANSACTION;
DELETE FROM accounts WHERE id = 2;

-- SESSION 1:
START TRANSACTION;
SELECT * FROM accounts;
COMMIT;

-- SESSION 2:
COMMIT;

